#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.silentgear]
			netherwood = true

		[types.leaves_type.silentgear]
			netherwood = true

#Disables specific entries
[entries]

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			trim = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.another_furniture]
			table = true
			flower_box = true
			shelf = true
			drawer = true
			shutter = true
			bench = true
			chair = true

		[entries.wood_type.beautify]
			trellis = true
			blinds = true
			picture_frame = true

		[entries.wood_type.farmersdelight]
			cabinet = true
